platform :ios, '10'
use_frameworks!

target 'WeatherApp' do
  pod 'Alamofire', '~> 5.4'
  pod 'IQKeyboardManagerSwift', '~> 6.1.1'
  pod 'RSFontSizes', '~> 1.0.2'
  pod 'R.swift', '~> 5.0.3'
  pod 'SwiftLint', '~> 0.43.1'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'SDWebImage', '~> 5.0'

  target 'WeatherAppUITests' do
    inherit! :complete
    pod 'Swifter', '~> 1.4.7'
  end
end
